name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Pull Tags
        run: git pull --tags

      - name: Setup PNPM and Node
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          publish-script: pnpm changeset git-tag
          pr-title: Release package(s)
          commit-message: release package(s)

  convert-to-object:
    name: Convert to Object
    runs-on: ubuntu-slim
    needs: release
    outputs:
      packagesRecord: ${{ steps.convert.outputs.result }}
    steps:
      - name: Convert
        id: convert
        run: |
          converted=$(echo '${{ needs.release.outputs.publishedPackages }}' | jq -c 'reduce .[] as $item ({}; .[$item.name] = $item.version)')
          echo "result=$converted" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Production
    needs: convert-to-object
    if: fromJSON(needs.convert-to-object.outputs.packagesRecord)['petri-net-editor']
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit

  docker:
    name: Build and Push Docker Image
    needs: convert-to-object
    if: fromJSON(needs.convert-to-object.outputs.packagesRecord)['petri-net-editor']
    uses: docker/github-builder/.github/workflows/build.yml@c4a1b216d96a8c85b45a9974b37857828274c808 # v1
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: .
      file: Dockerfile
      meta-images: ghcr.io/nimec01/petri-net-editor
      meta-tags: |
        type=sha
        type=pep440,pattern={{version}},value=${{ fromJSON(needs.convert-to-object.outputs.packagesRecord)['petri-net-editor'] }}
      meta-flavor: |
        latest=true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: nimec01
          password: ${{ secrets.GITHUB_TOKEN }}
