name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Pull Tags
        run: git pull --tags

      - name: Setup PNPM and Node
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@198f833dd7d863100ea6e28967bc9a9fdefadb0a # v2.1.0
        with:
          publish: pnpm changeset tag
          title: Release package(s)
          commit: release package(s)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
